config/routes.rb
Lman::Application.routes.draw do
  resources :mods

  resources :kategories

  resources :courses

    netzke
    root :to => 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :kategory
  has_many :mods
end

app/models/kategory.rb
class Kategory < ActiveRecord::Base
has_many :mods, :through => :courses
  has_many :courses




end

app/models/kurs.rb
class Kurs < ActiveRecord::Base
  belongs_to :modul
  has_and_belongs_to_many :progs
  has_many :kursdates
end

app/models/kursdate.rb
class Kursdate < ActiveRecord::Base
  belongs_to :kurs
end

app/models/mod.rb
class Mod < ActiveRecord::Base
  belongs_to :course
end

app/models/modul.rb
class Modul < ActiveRecord::Base
  belongs_to :prog
  has_many :kurses

end

app/models/prog.rb
class Prog < ActiveRecord::Base
  has_many :moduls
  has_and_belongs_to_many :kurses
end

app/models/progs_kurs.rb
class ProgsKurs < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :name
    default_scope :conditions => {:done => false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end
end

app/controllers/kategories_controller.rb
class KategoriesController < ApplicationController
  # GET /kategories
  # GET /kategories.json
  def index
    @kategories = Kategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kategories }
    end
  end

  # GET /kategories/1
  # GET /kategories/1.json
  def show
    @kategory = Kategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kategory }
    end
  end

  # GET /kategories/new
  # GET /kategories/new.json
  def new
    @kategory = Kategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kategory }
    end
  end

  # GET /kategories/1/edit
  def edit
    @kategory = Kategory.find(params[:id])
  end

  # POST /kategories
  # POST /kategories.json
  def create
    @kategory = Kategory.new(params[:kategory])

    respond_to do |format|
      if @kategory.save
        format.html { redirect_to @kategory, notice: 'Kategory was successfully created.' }
        format.json { render json: @kategory, status: :created, location: @kategory }
      else
        format.html { render action: "new" }
        format.json { render json: @kategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kategories/1
  # PUT /kategories/1.json
  def update
    @kategory = Kategory.find(params[:id])

    respond_to do |format|
      if @kategory.update_attributes(params[:kategory])
        format.html { redirect_to @kategory, notice: 'Kategory was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @kategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kategories/1
  # DELETE /kategories/1.json
  def destroy
    @kategory = Kategory.find(params[:id])
    @kategory.destroy

    respond_to do |format|
      format.html { redirect_to kategories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  # GET /mods
  # GET /mods.json
  def index
    @mods = Mod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mods }
    end
  end

  # GET /mods/1
  # GET /mods/1.json
  def show
    @mod = Mod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mod }
    end
  end

  # GET /mods/new
  # GET /mods/new.json
  def new
    @mod = Mod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mod }
    end
  end

  # GET /mods/1/edit
  def edit
    @mod = Mod.find(params[:id])
  end

  # POST /mods
  # POST /mods.json
  def create
    @mod = Mod.new(params[:mod])

    respond_to do |format|
      if @mod.save
        format.html { redirect_to @mod, notice: 'Mod was successfully created.' }
        format.json { render json: @mod, status: :created, location: @mod }
      else
        format.html { render action: "new" }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mods/1
  # PUT /mods/1.json
  def update
    @mod = Mod.find(params[:id])

    respond_to do |format|
      if @mod.update_attributes(params[:mod])
        format.html { redirect_to @mod, notice: 'Mod was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mods/1
  # DELETE /mods/1.json
  def destroy
    @mod = Mod.find(params[:id])
    @mod.destroy

    respond_to do |format|
      format.html { redirect_to mods_url }
      format.json { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/kategories_helper.rb
module KategoriesHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_c %><br />
    <%= f.text_field :name_c %>
  </div>
  <div class="field">
    <%= f.label :kategory_id %><br />
    <%= f.number_field :kategory_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name c</th>
    <th>Kategory</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name_c %></td>
    <td><%= course.kategory_id %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name c:</b>
  <%= @course.name_c %>
</p>

<p>
  <b>Kategory:</b>
  <%= @course.kategory_id %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/kategories/_form.html.erb
<%= form_for(@kategory) do |f| %>
  <% if @kategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kategory.errors.count, "error") %> prohibited this kategory from being saved:</h2>

      <ul>
      <% @kategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_k %><br />
    <%= f.text_field :name_k %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kategories/edit.html.erb
<h1>Editing kategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @kategory %> |
<%= link_to 'Back', kategories_path %>

app/views/kategories/index.html.erb
<h1>Listing kategories</h1>

<table>
  <tr>
    <th>Name k</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kategories.each do |kategory| %>
  <tr>
    <td><%= kategory.name_k %></td>
    <td><%= link_to 'Show', kategory %></td>
    <td><%= link_to 'Edit', edit_kategory_path(kategory) %></td>
    <td><%= link_to 'Destroy', kategory, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kategory', new_kategory_path %>

app/views/kategories/new.html.erb
<h1>New kategory</h1>

<%= render 'form' %>

<%= link_to 'Back', kategories_path %>

app/views/kategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name k:</b>
  <%= @kategory.name_k %>
</p>


<%= link_to 'Edit', edit_kategory_path(@kategory) %> |
<%= link_to 'Back', kategories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Netzke Task Manager</title>
  <%= netzke_init %>
  <style type="text/css" media="screen">
    h1 { text-align: center; margin: 10px;}
    .netzke-component { width: 700px; margin: auto; }
  </style>

  <%= csrf_meta_tag %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/mods/_form.html.erb
<%= form_for(@mod) do |f| %>
  <% if @mod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mod.errors.count, "error") %> prohibited this mod from being saved:</h2>

      <ul>
      <% @mod.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_m %><br />
    <%= f.text_field :name_m %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :kategory_id %><br />
    <%= f.number_field :kategory_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mods/edit.html.erb
<h1>Editing mod</h1>

<%= render 'form' %>

<%= link_to 'Show', @mod %> |
<%= link_to 'Back', mods_path %>

app/views/mods/index.html.erb
<h1>Listing mods</h1>

<table>
  <tr>
    <th>Name m</th>
    <th>Course</th>
    <th>Kategory</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mods.each do |mod| %>
  <tr>
    <td><%= mod.name_m %></td>
    <td><%= mod.course_id %></td>
    <td><%= mod.kategory_id %></td>
    <td><%= link_to 'Show', mod %></td>
    <td><%= link_to 'Edit', edit_mod_path(mod) %></td>
    <td><%= link_to 'Destroy', mod, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mod', new_mod_path %>

app/views/mods/new.html.erb
<h1>New mod</h1>

<%= render 'form' %>

<%= link_to 'Back', mods_path %>

app/views/mods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name m:</b>
  <%= @mod.name_m %>
</p>

<p>
  <b>Course:</b>
  <%= @mod.course_id %>
</p>

<p>
  <b>Kategory:</b>
  <%= @mod.kategory_id %>
</p>


<%= link_to 'Edit', edit_mod_path(@mod) %> |
<%= link_to 'Back', mods_path %>

app/views/welcome/index.html.erb
 <h1><b> Администрирование </b>  </h1>

 <h2 align="center">Добавление Программ:</h2>

 <%= netzke :kategories,
   :class_name => "Netzke::Basepack::GridPanel",
   :model => "Kategory",
   :columns => [:id,
                :name_k,





   ],
   # Standard Ext.grid.EditorGridPanel configuration options:
   :border => true,
   :header => false,
   :view_config => {
     :force_fit => true # force the columns to occupy all the available width
   }
 %>
 <br>

<h2 align="center">Добавление Курсов</h2>

<%= netzke :courses,
  :class_name => "Netzke::Basepack::GridPanel",
  :model => "Course",
  :columns => [:id, :name_c,


              :kategory__name_k
  ],
  # Standard Ext.grid.EditorGridPanel configuration options:
  :border => true,
  :header => false,
  :view_config => {
    :force_fit => true # force the columns to occupy all the available width
  }
%>


 <br>

 <h2 align="center">Добавление Модуей</h2>

 <%= netzke :mods,
   :class_name => "Netzke::Basepack::GridPanel",
   :model => "Mod",
   :columns => [:id, :name_m,

           :course__name_c,
           :kategory__name_k

   ],
   # Standard Ext.grid.EditorGridPanel configuration options:
   :border => true,
   :header => false,
   :view_config => {
     :force_fit => true # force the columns to occupy all the available width
   }
 %>


 <br>